todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('list_category/', views.ListCategoryView.as_view(), name='list_category'),
    path('new/', views.CreateTodoView.as_view(), name='new_todo'),
    path('<int:category_pk>/new/', views.CreateTodoWithCategoryView.as_view(), name='new_todo_category'),
    path('<int:pk>/list/', views.ListTodoView.as_view(), name='list_todo'),
    path('<int:pk>/<int:cat_pk>/delete/', views.DeleteTodoView.as_view(), name='delete_todo'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update_todo'),
    path('<int:pk>/detail/', views.DetailTodoView.as_view(), name='detail_todo'),
    path('<int:pk>/todo_done/', views.todo_done, name='todo_done'),
    path('<int:pk>/completed_todo', views.ListCompletedTodoView.as_view(), name='completed_todo'),

    #Categories urls
    path('category/new/', views.CreateCategoryView.as_view(), name='new_category'),
    path('category/<int:pk>/delete', views.DeleteCategoryView.as_view(), name='delete_category'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.utils import timezone

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length = 50, null=False)
    text = models.CharField(max_length = 150, null=False)
    author = models.ForeignKey(
        User,
        on_delete = models.CASCADE
        )
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE
    )
    created = models.DateField(default=timezone.now(), editable=True)
    completed = models.BooleanField(null=False, blank=False, default=False)

    completed_date = models.DateField(null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('list_todo', kwargs={'pk':self.category.id})

    def save(self, *args, **kwargs):
        if self.completed:
            self.completed_date = timezone.now()
        return super(Todo, self).save(*args, **kwargs)

class Category(models.Model):
    title = models.CharField(max_length=140)
    author = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('list_category')

    @property
    def get_todos(self):
        return Todo.objects.filter(category__id=self.id)

templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}To-Do List{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="{% url 'home' %}">To-Do List</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id='navbarNav'>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'list_category' %}">Category</a>
                </li>
                {% block extra_nav %}

                {% endblock %}
                    
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="btn btn-primary navbar-btn mr-2">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'signup' %}" class="btn btn-success navbar-btn">Sign up</a>

                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/category_list.html
{% extends 'base.html' %}

{% block extra_nav %}
{% if object_list %}
<li class="nav-item">
        <a class="nav-link" href="{% url 'new_todo' %}">+ New To-Do</a>
</li>
{% endif %}
{% endblock extra_nav%}

{% block content %}
    {% if object_list %}
        <a href="{% url 'new_category' %}" class="btn btn-success mb-3">New Category</a>
        <h1 class="mb-3">Categories</h1>
        <p>{{ Todo_count }} tasks in {{ Cat_count }} category.</p>
        {% for category in object_list %}
        <div class="list-group">
            <a href="{% url 'list_todo' category.pk %}" type="button" class="list-group-item list-group-item-action mb-1">
                {{ category.title }}
                <span class="badge badge-primary badge-pill ml-2">{{ category.todo_set.count }}</span>
            </a>
        </div>
        {% endfor %}
    {% else %}
        <h1 class="display-2">Empty</h1>
        <p class="mt-2">There aren't categories or tasks. Click New Category to add a Category.</p>
        <a href="{% url 'new_category' %}" class="btn btn-success mb-3">New Category</a>
    {% endif %}
{% endblock %}

templates/completed_todo.html
{% extends "base.html" %}
{% block title %}Completed TODOs{% endblock %}

{% block content %}
<h1 class='mb-3'>Tasks completed in ({{category}})</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Owner</th>
            <th scope="col">Created</th>
            <th scope="col">Completed</th>
            <th scope="col">Mark</th>
        </tr>
    </thead>
    <tbody>
        {% for todo in object_list %}
        {% if todo.completed %}
            <tr>
                <td><a href="{% url 'detail_todo' todo.pk %}">{{ todo.title }}</a></td>
                <td>{{ todo.author }}</td>
                <td>{{ todo.created }}</td>
                <td>{{ todo.completed_date }}</td>
                <td>
                    <form method="POST" action="{% url 'todo_done' todo.id %}" role="form">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-sm">Undone</button>
                    </form>
                </td>
            </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>

<a href='{% url "list_todo" category.pk %}' class="btn btn-danger">Back to Tasks</a>
{% endblock %}

templates/delete_todo.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object.title }}" by {{ object.author }} ?</p>
        <button type='submit' class="btn btn-danger" type="submit">Confirm</button>
        <a href="{% url 'detail_todo' todo.pk %}" class="btn btn-primary">Cancel</a>
    </form>
{% endblock %}

templates/detail_todo.html
{% extends "base.html" %}
{% block title %}Detail Todo{% endblock %}

{% block content %}
    <a href="{% url 'list_todo' todo.category.pk %}" class="btn btn-success mb-3">Back to Task List</a>
    <h1>{{ todo.title }}</h1>
    <p>{{ todo.text }}</p>
    <p><strong>Author:</strong> {{ todo.author }}</p>
    <p><strong>Created:</strong> {{ todo.created }}</p>
    {% if todo.completed %}<p><strong>Completed:</strong> {{ todo.completed_date }}</p>{% endif %}
    <a href="{% url 'update_todo' todo.pk %}" class="btn btn-primary">Edit Task</a>
    {% if todo.completed %}
        <a href="{% url 'todo_done' todo.pk %}" class="btn btn-info">Mark Not Done</a>
    {% else %}
        <a href="{% url 'todo_done' todo.pk %}" class="btn btn-info">Mark Done</a>
    {% endif %}
    <a href="{% url 'delete_todo' todo.pk todo.category.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-1">Todo App</h1>
        <p class="lead">A Todo website built in Django.</p>
        <a class="btn btn-primary btn-lg" href="{% url 'list_category' %}" role="button">See all Categories</a>
    </div>

{% endblock %}

templates/new_todo.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}New To-Do{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button class="btn btn-success" type="submit">Save</button>
        {% if category %}
            <a href="{% url 'list_todo' category %}" class="btn btn-danger">Cancel</a>
        {% else %}
            <a href="{% url 'home' %}" class="btn btn-danger">Cancel</a>
        {% endif %}
    </form>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block title %}Signup{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Confirm</button>
    </form>
{% endblock %}

templates/todo_list.html
{% extends 'base.html' %}

{% block extra_nav %}
    {% if object_list %}
    <li class="nav-item">
            <a class="nav-link" href="{% url 'new_todo' %}">+ New To-Do</a>
    </li>
    {% endif %}
{% endblock extra_nav%}

{% block content %}
<a href="{% url 'new_todo_category' category.pk %}" class="btn btn-success mb-3">Add new task</a>
<h1 class='mb-3'>Tasks in ({{category}})</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Owner</th>
            <th scope="col">Created</th>
            <th scope="col">Mark</th>
        </tr>
    </thead>
    <tbody>
        {% for todo in object_list %}
        {% if todo.completed %}

        {% else %}
        <tr>
            <td><a href="{% url 'detail_todo' todo.pk %}">{{ todo.title }}</a></td>
            <td>{{ todo.author }}</td>
            <td>{{ todo.created }}</td>
            <td>
                <form method="POST" action="{% url 'todo_done' todo.id %}" role="form">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">Done</button>
                </form>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>

<a href='{% url "completed_todo" category.pk %}' class="btn btn-warning">Tasks completed</a>
<a href="{% url 'delete_category' category.pk %}" class="btn btn-danger">Delete this list</a>

{% endblock %}

templates/update_todo.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Update To-Do{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Update</button>
        <a href="{% url 'detail_todo' todo.pk %}" class="btn btn-danger">Cancel</a>
    </form>
{% endblock %}